---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  labels:
    name: kafdrop
  namespace: comm-infra
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 9000
    targetPort: 9000
    nodePort: 30002
  selector:
    name: kafdrop
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  labels:
    name: kafdrop
  namespace: comm-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafdrop
  template:
    metadata:
      labels:
        name: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop
        env:
         - name: KAFKA_BROKERCONNECT
           value: "cluster-kafka-bootstrap:9092"
        ports:
        - containerPort: 9000