---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
  namespace: sock-shop
spec:
  ports:
  - port: 9092
    name: client-port
    targetPort: 9092
  - port: 29092
    name: other-host
    targetPort: 29092
  selector:
    name: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    name: kafka
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          env:
           - name: KAFKA_BROKER_ID
             value: "1"
           - name: KAFKA_ZOOKEEPER_CONNECT
             value: "zookeeper:2181"
           - name: KAFKA_ADVERTISED_LISTENERS
             value: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
           - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
             value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
           - name: KAFKA_INTER_BROKER_LISTENER_NAME
             value: PLAINTEXT
           - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
             value: "1"
          ports:
           - containerPort: 9092
           - containerPort: 29092