---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
  namespace: sock-shop
spec:
  ports:
  - port: 2181
    name: client-port
    targetPort: 2181
  selector:
    name: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    name: zookeeper
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          env:
           - name: ZOOKEEPER_CLIENT_PORT
             value: "2181"
           - name: ZOOKEEPER_TICK_TIME
             value: "2000"
          ports:
           - containerPort: 2181