apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-service-monitor
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
  namespaceSelector:
    matchNames:
      - comm-infra
  endpoints:
  - port: metrics
    honorLabels: true
    interval: 10s
    scrapeTimeout: 10s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoints_name]
      separator: ;
      regex: prometheus-kube-state-metrics
      replacement: $1
      action: keep
  - port: metrics
    honorLabels: true
    interval: 10s
    scrapeTimeout: 10s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoints_name]
      separator: ;
      regex: prometheus-node-exporter
      replacement: $1
      action: keep