version: "3.3"
services:
  balancer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOOTSTRAP_SERVER: "192.168.49.2:30962"
      TOPIC_NAME: "my-topic"
    network_mode: "host"

